require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.3
  # rubocopの新機能をactiveにする
  NewCops: enable
  Exclude:
    - 'assets/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/migrate/**/*'

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可
Style/Documentation:
  Enabled: false

# frozen_string_literal の指定強制を解除
Style/FrozenStringLiteralComment:
  Enabled: false

# 1行の最大
Layout/LineLength:
  Max: 160

# 文字列はダブルクォートに統一
Style/StringLiterals:
  EnforcedStyle: double_quotes

# %w, %iの使用強制を解除(使用しても使用しなくてもOK)
Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20220911112952_devise_create_users.rb'
