databases:
  - name: oneday_app_db
    databaseName: oneday_app_production
    region: singapore
    plan: free

services:
  - type: web
    name: oneday_app_web
    env: ruby
    region: singapore
    plan: free
    branch: master
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oneday_app_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
